### ISSUE TITLE
Undocumentated cronjob commands

### ISSUE THREAD

**Issue by pseiler** [opnsense/docs#282]
I at least use this cronjob "Periodic interface reset" to renew my PPPoE IP address over-night.

I googled to find out that I need to put "wan" into the parameters to get it working. This isn't documented anywhere.
So could you please add information about the available (optional) parameters to the documentation or explain it here and I work these infos into the documentation and send a pull request. Also some of the cronjobs seem to be outdated/redundant to some other built-in features.

* These are the commands I'm talking about:
* Automatic Firmware Update
* Download and reload external proxy ACLs
* Download external proxy ACLs
* Dynamic DNS Update
* Firmware changelog update
* Issue a reboot
* Periodic interface reset -> params: "wan"
* Reconfigure a plugin facility
* Regenerate DH parameters
* Reload intrusion detection rules
* Remote backup
* Restart Captive Portal service
* Restart IPSec service
* Update and reload firewall aliases
* Update and reload intusion detection rules

**Comment by fichtner** [comment]
These are in my opinion as is commands request previously. One thing we have in mind, however, is making parameters a preselected drop down box as that actually makes sense. Most cron jobs are supposed to be taken without parameters also.

**Comment by pseiler** [comment]
This unfortunatley doesn't answer my question. I wanted to know what (optional) parameters every command can take.
I only found out that the one I mentioned can take "wan". And if it's omitted it also will also take the default "wan".
I want to documentate this until the parameters will be replaced with a drop-down selection box.

**Comment by fichtner** [comment]
I am aware it doesn't answer your question. It differs for each script and as backend scripts evolve it will probably change. We should probably not want to document moving backend parts.

**Comment by pseiler** [comment]
Thank you very much for the answer. Looking forward to the dropdown selection solution!

**Comment by pseiler** [comment]
If you guys could tell me all parameters which have useful parameters you could still write them down so maybe I try to implement the checkboxes myself.

**Comment by AdSchellevis** [comment]
Hi Philipp, 

You probably best track the configd templates, most of them don't accept parameters.
https://github.com/opnsense/core/blob/6cc719a50761cf4e419abe7b94fd0d513b2346b4/src/opnsense/service/conf/actions.d/actions_interface.conf#L1-L6

The trick is actually pretty simple, if there's a description available, it will be visible in the ui, we (currently) don't offer a mechanism to propagate viable options or validations. Personally I don't think there's a lot of value it it either, since most of the tasks are quite self explanatory and either managed from a different entry point (IDPS) or used for rare edge cases (reboot once a day, who would want that in stable environments :) ).

More info available in the docs here https://docs.opnsense.org/development/backend/configd.html#action-properties

Best regards,

Ad
