### ISSUE TITLE
Adding Log section to documentation

### ISSUE THREAD

**Issue by mimugmail** [opnsense/docs#67]
Will add this the next days

**Comment by soder10** [comment]
Hello @mimugmail is there any place I can check this?

**Comment by soder10** [comment]
Just 2 remarks from my side:

1) /var/log/flowd* is not mentioned in this list. If I am correct, they contain the so called "insight cache", that has 10 files, eaxh approx 10 mb max. so the product is max 100 mb for this functionality.

2) /var/log/gateways.log: All the docs says is: "All about gateway tracking"

That is a little bit vague description for me. Would be more precise to say: Apinger/Dpinger (the former one is already deprecated since 19.1) gateway tracking logs.
But then comes the surprise: on a default installation this file is completely empty, egen if my gateway says ONLINE! How  can this gateway tracking be working then? Its simple, because this gazeway tracking is inactive by default. The gateway status marks green/ONLINE because the setting: Disable Gateway Monitoring : This will consider this gateway as always being "up" is enabled by default, and dpinger does nothing. So the log is empty. This hidden fact should be at least mentioned under gateway tracking loggin, that by default is not tracking the gateway status, in order to see log activity, UNCHECK the disable monitoring first!

I hope these 2 remarks can make their way to the docs.

**Comment by mimugmail** [comment]
If you fine a neat space where this info could fit in, just edit the file and open a PR. You have the same rights like me :)
